nova.require "trial_gfx/entities/arch_fiend"
nova.require "trial_gfx/entities/cultist"
nova.require "trial_gfx/entities/drone_printer"
nova.require "trial_gfx/entities/medusalings"
nova.require "trial_gfx/entities/paladin_human"
nova.require "trial_gfx/entities/wither_watcher"