nova.require "trial_data/entities/arch_fiend"
nova.require "trial_data/entities/cultist"
nova.require "trial_data/entities/medusalings"
nova.require "trial_data/entities/paladin_human"
nova.require "trial_data/entities/wither_watcher"